cd: new test 3

diff --git a/.github/workflows/CD-Lambda-Test.yml b/.github/workflows/CD-Lambda-Test.yml
--- a/.github/workflows/CD-Lambda-Test.yml
+++ b/.github/workflows/CD-Lambda-Test.yml
@@ -33,8 +33,7 @@ jobs:
     - name: Load environment variables from JSON
       id: load-env
       run: |
-        ENV_VARS=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' env_vars.json)
-        echo "$ENV_VARS" >> $GITHUB_ENV
+        cat env_vars.json | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' >> $GITHUB_ENV || echo "Failed to load environment variables"
 
     - name:  Print loaded environment variables
       run: |
@@ -45,10 +44,10 @@ jobs:
       run: |
         tail -n 5 $GITHUB_ENV
     - run: npm ci
-    - name: serverless deploy
-      uses: serverless/github-action@v3.2
-      with:
-        args: deploy
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROHEM }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROHEM }}
+    # - name: serverless deploy
+    #   uses: serverless/github-action@v3.2
+    #   with:
+    #     args: deploy
+    #   env:
+    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ROHEM }}
+    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ROHEM }}
